
export interface LoreEntry {
  id: string;
  name: string;
  category: 'Character' | 'Location' | 'Item' | 'Rule';
  description: string;
}

export interface StoryConfig {
  corePremise: string;
  genre: string;
  tone: string;
  narrativeStyle: string;
  targetAudience: string;
  lengthStructure: string;
  chapterCount: string;
  keyElements: string;
  complexity: string;
  endingType: string;
  constraints: string;
  existingContent?: string;
  lore?: LoreEntry[];
}

export interface QuestionOption {
  label: string;
  value: string;
}

export enum AppView {
  WIZARD = 'WIZARD',
  STORY_RESULT = 'STORY_RESULT',
  IMAGE_STUDIO = 'IMAGE_STUDIO',
  INFOGRAPHICS = 'INFOGRAPHICS',
  PUBLISHER = 'PUBLISHER',
  DASHBOARD = 'DASHBOARD',
  HISTORY = 'HISTORY',
  CHAT = 'CHAT'
}

export interface ChatMessage {
  role: 'user' | 'model';
  text: string;
  timestamp: number;
  attachments?: string[]; // Base64 strings of uploaded images
  generatedImage?: string; // Base64 string of the image generated by the model
}

export interface ChatSession {
  id: string;
  title: string;
  timestamp: number;
  messages: ChatMessage[];
}

export interface PublishingConfig {
  coverImage?: string; // Base64
  coverStyle?: string;
  coverResolution?: '1K' | '2K' | '4K';
  backCoverBlurb?: string;
  includeTOC?: boolean;
  paperSize?: '5x8' | '6x9' | 'A5' | 'A4' | 'Letter';
  margins?: 'narrow' | 'normal' | 'wide';
  layout: {
    headingFont: string;
    bodyFont: string;
    fontSize: number;
    dropCaps: boolean;
  };
  metadata: {
    author: string;
    dedication: string;
    copyright: string;
    isbn?: string;
  };
  extraSections: {
    id: string;
    title: string;
    content: string;
    type: 'preface' | 'epilogue' | 'custom';
  }[];
}

export interface HistoryItem {
  id: string;
  timestamp: number;
  title: string;
  excerpt: string;
  content: string;
  config: StoryConfig;
  lore: LoreEntry[];
  publishingConfig?: PublishingConfig;
}

export interface ImageHistoryItem {
  id: string;
  timestamp: number;
  prompt: string;
  imageData: string;
  mode: 'CREATE' | 'EDIT';
  aspectRatio?: string;
}

export interface InfographicItem {
  id: string;
  title: string;
  summary: string;
  visualPrompt: string;
  imageData?: string;
  status: 'pending' | 'generating' | 'done' | 'failed';
  aspectRatio?: string;
  // Chart specific
  isChart?: boolean;
  chartType?: 'Bar' | 'Line' | 'Pie' | 'Area';
  chartDataSummary?: string; 
}

export interface PageData {
  content: string;
  chapterTitle: string;
  pageNumber: number;
}
