export interface StoryConfig {
  corePremise: string;
  genre: string;
  tone: string;
  narrativeStyle: string;
  targetAudience: string;
  lengthStructure: string;
  chapterCount: string;
  keyElements: string;
  complexity: string;
  endingType: string;
  constraints: string;
  existingContent?: string;
}

export interface QuestionOption {
  label: string;
  value: string;
}

export enum AppView {
  WIZARD = 'WIZARD',
  STORY_RESULT = 'STORY_RESULT',
  IMAGE_STUDIO = 'IMAGE_STUDIO',
  INFOGRAPHICS = 'INFOGRAPHICS',
  DASHBOARD = 'DASHBOARD',
  HISTORY = 'HISTORY',
  CHAT = 'CHAT'
}

export interface ChatMessage {
  role: 'user' | 'model';
  text: string;
  timestamp: number;
  attachment?: string; // Base64 string of the uploaded image
  generatedImage?: string; // Base64 string of the image generated by the model
}

export interface ChatSession {
  id: string;
  title: string;
  timestamp: number;
  messages: ChatMessage[];
}

export interface HistoryItem {
  id: string;
  timestamp: number;
  title: string;
  excerpt: string;
  content: string;
  config: StoryConfig;
}

export interface ImageHistoryItem {
  id: string;
  timestamp: number;
  prompt: string;
  imageData: string;
  mode: 'CREATE' | 'EDIT';
  aspectRatio?: string;
}

export interface InfographicItem {
  id: string;
  title: string;
  summary: string;
  visualPrompt: string;
  imageData?: string;
  status: 'pending' | 'generating' | 'done' | 'failed';
  aspectRatio?: string;
}

export interface PageData {
  content: string;
  chapterTitle: string;
  pageNumber: number;
}